/**
 * Framework catalog — single source of truth.
 *
 * fields:
 *  id          stable identifier
 *  name        display name
 *  category    one of CATEGORIES keys
 *  kind        "formal" (paper-backed / established) | "informal" (descriptive / emerging)
 *  shape      one-line geometry of the reasoning
 *  useCase     when to reach for it
 *  instruction the imperative handed to the model
 *  orchestrated true => engine runs multiple model calls; otherwise single-prompt simulation
 *  note        honesty note about simplifications, if any
 */

export const CATEGORIES = {
  linear:      "1. Linear / sequential (one path)",
  branching:   "2. Branching / search (explore + prune)",
  hierarchical:"3. Hierarchical / top-down (parent constrains child)",
  agentic:     "4. Agentic / action + tool use (reason ↔ act loops)",
  selfcheck:   "5. Self-improvement / verification",
  ensemble:    "6. Ensemble / aggregation",
  patterns:    "7. Other structured prompting patterns",
  transfer:    "8. Transfer & adaptation (cross-domain)"
};

export const FRAMEWORKS = [
  /* ============ 1. LINEAR ============ */
  { id:"cot", name:"Chain of Thought (CoT)", category:"linear", kind:"formal",
    shape:"step → step → step",
    useCase:"Steps are knowable; execute a sequence cleanly.",
    instruction:"Think step by step in ONE linear path. Number each step, state the decision and why, never skip ahead. End with the final answer." },
  { id:"zeroshot-cot", name:"Zero-shot CoT", category:"linear", kind:"formal",
    shape:"'let's think step by step'",
    useCase:"Quick uplift on any task with zero setup.",
    instruction:"Let's think step by step. Work through the problem carefully before giving the final answer." },
  { id:"fewshot-cot", name:"Few-shot CoT", category:"linear", kind:"formal",
    shape:"worked examples → same pattern",
    useCase:"You can show 1-3 worked examples of the reasoning you want.",
    instruction:"First write ONE brief worked example of solving a structurally similar (but different) problem step by step. Then solve the actual task following exactly the same reasoning pattern." },
  { id:"chain-of-draft", name:"Chain of Draft / Density", category:"linear", kind:"formal",
    shape:"draft₁ → denser draft₂ → draft₃",
    useCase:"Compression and refinement of an answer over passes.",
    instruction:"Produce DRAFT 1 (quick, loose). Then DRAFT 2: same content, denser and sharper. Then DRAFT 3: the tightest, highest-quality version. Show all three." },
  { id:"least-to-most", name:"Least-to-Most", category:"linear", kind:"formal",
    shape:"easy sub-problems → hard whole",
    useCase:"Big tasks that decompose; earlier answers feed later ones.",
    instruction:"Decompose into sub-problems ordered easiest → hardest. Solve each in order, explicitly REUSING earlier answers. Assemble the final solution from the parts." },
  { id:"step-back", name:"Step-Back", category:"linear", kind:"formal",
    shape:"abstract principle → apply",
    useCase:"Surface details mislead; the general principle unlocks it.",
    instruction:"First step back: state the GENERAL PRINCIPLE or abstraction governing this task (not its surface details). Then apply that principle to solve the concrete task." },
  { id:"plan-and-solve", name:"Plan-and-Solve", category:"linear", kind:"formal",
    shape:"write plan → execute plan",
    useCase:"Skipped steps are costly; force explicit planning.",
    instruction:"First write a numbered PLAN covering every step. Then EXECUTE the plan step by step, marking each as done. Do not deviate without saying why." },

  /* ============ 2. BRANCHING ============ */
  { id:"tot", name:"Tree of Thoughts (ToT)", category:"branching", kind:"formal",
    shape:"branch → score → prune → expand",
    useCase:"Direction is genuinely open; explore before committing.",
    instruction:"Generate 3 DISTINCT candidate approaches (A, B, C). For each: pros, cons, score /10 on feasibility × impact × fit. PRUNE the losers, then EXPAND the winner into a full solution." },
  { id:"got", name:"Graph of Thoughts (GoT)", category:"branching", kind:"formal",
    shape:"branch → MERGE → refine",
    useCase:"The best answer is a hybrid of partial ideas.",
    instruction:"Generate 4 partial ideas. Identify which pairs are compatible and MERGE them into hybrid candidates. Evaluate the hybrids and develop the strongest into the final answer." },
  { id:"forest", name:"Forest of Thoughts", category:"branching", kind:"informal",
    shape:"many independent trees → ensemble",
    useCase:"High-variance creative tasks; reduce luck via independent explorations.",
    orchestrated:true,
    instruction:"Run an independent Tree-of-Thoughts exploration and give your single best resulting answer.",
    note:"Engine runs 3 independent ToT passes, then an aggregator call combines/votes." },
  { id:"mcts", name:"MCTS-style reasoning", category:"branching", kind:"formal",
    shape:"simulate rollouts → backpropagate scores",
    useCase:"Sequential decisions where you can simulate outcomes.",
    instruction:"Treat this as search: propose 3 first-moves; for each, SIMULATE a quick rollout of how it plays out; score the end state /10; pick the first-move with the best rollout and develop it fully.",
    note:"Single-prompt simulation. True MCTS needs many programmatic rollouts." },
  { id:"beam", name:"Beam search reasoning", category:"branching", kind:"formal",
    shape:"keep top-k partial paths each step",
    useCase:"Long generations where early commitment is risky.",
    instruction:"Solve in 3 stages. At each stage keep the TOP-2 partial solutions (the beam), discard the rest, and extend both into the next stage. At the end, output the best complete path and say why it beat the other." },

  /* ============ 3. HIERARCHICAL ============ */
  { id:"cascade", name:"Hierarchical Cascade", category:"hierarchical", kind:"informal",
    shape:"L0 ▼ L1 ▼ L2 ▼ leaf (inherit downward)",
    useCase:"Many outputs must stay consistent with one strategy.",
    instruction:"Decompose top-down. L0: the governing strategy/constraints. L1: direction that INHERITS L0. L2: components that INHERIT L1. L3: execution details that INHERIT L2. State the inherited constraint at every level." },
  { id:"decomp", name:"Recursive Decomposition", category:"hierarchical", kind:"formal",
    shape:"task → sub-tasks → sub-sub-tasks",
    useCase:"Heterogeneous tasks whose parts need different treatment.",
    instruction:"Recursively decompose the task into sub-tasks until each is trivially solvable. Solve the leaves, then compose the solutions back up the tree. Show the tree." },
  { id:"htn", name:"HTN-style planning", category:"hierarchical", kind:"formal",
    shape:"abstract task → methods → primitive actions",
    useCase:"Procedural goals with known method libraries.",
    instruction:"Treat the goal as an abstract task. Decompose it via METHODS into ordered sub-tasks, recursing until every leaf is a primitive, directly-executable action. Output the resulting ordered action plan." },
  { id:"sot", name:"Skeleton-of-Thought", category:"hierarchical", kind:"formal",
    shape:"outline skeleton → expand each point",
    useCase:"Long structured outputs, fast; parallelizable expansion.",
    instruction:"First output a SKELETON: one line per part of the answer. Then expand each skeleton point into its full content, independently." },

  /* ============ 4. AGENTIC ============ */
  { id:"react", name:"ReAct", category:"agentic", kind:"formal",
    shape:"Thought → Action → Observation ↻",
    useCase:"The task needs tools or external info mid-reasoning.",
    instruction:"Loop: THOUGHT (what do I need next?), ACTION (name the tool/lookup you would call and with what input), OBSERVATION (state the realistic result). Repeat until confident, then give the final answer.",
    note:"v1 simulates tool calls in-prompt; engine exposes a tools hook for real integrations." },
  { id:"rewoo", name:"ReWOO", category:"agentic", kind:"formal",
    shape:"plan all tool calls upfront → execute → solve",
    useCase:"Cut token/tool cost vs ReAct by planning calls once.",
    instruction:"First write the complete PLAN of every tool call you would need (tool + input), without executing. Then list the expected EVIDENCE each returns. Finally SOLVE using that evidence. Do not interleave." },
  { id:"reflexion", name:"Reflexion", category:"agentic", kind:"formal",
    shape:"act → feedback → self-reflection → retry",
    useCase:"Tasks you can attempt, evaluate, and retry better.",
    orchestrated:true,
    instruction:"Attempt the task.",
    note:"Engine: attempt → critique-as-feedback → written self-reflection → improved retry. 3 calls." },
  { id:"tool-chain", name:"Toolformer / Tool-use chaining", category:"agentic", kind:"formal",
    shape:"model decides when/which tools",
    useCase:"Open tasks where tool choice itself is the decision.",
    instruction:"Solve the task; whenever a step would benefit from a tool, write [TOOL: name(input)] inline at exactly the point you would call it, then continue with its assumed output. Choose tools judiciously.",
    note:"Simulated tool insertion; wire real tools via the engine hook." },
  { id:"plan-execute-replan", name:"Plan-Execute-Replan", category:"agentic", kind:"informal",
    shape:"plan → execute → check → replan ↻",
    useCase:"Long-horizon goals where plans go stale mid-flight.",
    instruction:"PLAN the task. EXECUTE step 1-2. Then STOP and CHECK: does the plan still hold? If not, REPLAN from current state. Repeat until done. Show each plan revision." },

  /* ============ 5. SELF-IMPROVEMENT / VERIFICATION ============ */
  { id:"self-consistency", name:"Self-Consistency", category:"selfcheck", kind:"formal",
    shape:"sample N paths → majority vote",
    useCase:"One answer you can't get wrong; variance reduction.",
    orchestrated:true,
    instruction:"Solve the task, reasoning independently.",
    note:"Engine: 3 independent samples, then a judge call reports the majority answer + agreement." },
  { id:"self-refine", name:"Self-Refine", category:"selfcheck", kind:"formal",
    shape:"draft → critique → revise ↻",
    useCase:"Polish; quality past the first draft.",
    orchestrated:true,
    instruction:"Draft an answer to the task.",
    note:"Engine: draft → harsh critique → revision. 3 calls." },
  { id:"cove", name:"Chain-of-Verification (CoVe)", category:"selfcheck", kind:"formal",
    shape:"draft → verify-questions → answer them → correct",
    useCase:"Factual reliability; catching your own errors.",
    orchestrated:true,
    instruction:"Draft an answer to the task.",
    note:"Engine: draft → generate & answer fact-check questions → corrected final. 3 calls." },
  { id:"self-ask", name:"Self-Ask", category:"selfcheck", kind:"formal",
    shape:"sub-questions → answers → conclusion",
    useCase:"Multi-hop questions hiding inside one question.",
    instruction:"Before answering, ask yourself the FOLLOW-UP QUESTIONS the task secretly requires. Answer each explicitly. Then compose the final answer from those answers." },
  { id:"constitutional", name:"Constitutional / critique-and-revise", category:"selfcheck", kind:"formal",
    shape:"draft → check vs principles → revise",
    useCase:"Outputs must conform to explicit principles/rules.",
    instruction:"Draft an answer. Then evaluate it against these principles: accurate, clear, complete, on-brief, honest about uncertainty. Revise to fix every violation. Output the revision and the violations you fixed." },
  { id:"debate", name:"Multi-agent Debate", category:"selfcheck", kind:"formal",
    shape:"A argues ↔ B rebuts → judge resolves",
    useCase:"Contested judgments; stress-testing a conclusion.",
    orchestrated:true,
    instruction:"Argue the strongest possible position on the task.",
    note:"Engine: advocate → opponent rebuttal → judge verdict. 3 calls." },

  /* ============ 6. ENSEMBLE ============ */
  { id:"moa", name:"Mixture-of-Agents", category:"ensemble", kind:"formal",
    shape:"specialists in parallel → aggregator",
    useCase:"Tasks spanning several kinds of expertise.",
    orchestrated:true,
    instruction:"Answer the task from your assigned specialist perspective.",
    note:"Engine: 3 specialist personas answer independently → aggregator synthesizes. 4 calls." },
  { id:"maieutic", name:"Maieutic prompting", category:"ensemble", kind:"formal",
    shape:"tree of explanations → resolve contradictions",
    useCase:"Consistency on ambiguous true/false-ish questions.",
    instruction:"Generate an explanation tree: the main claim, then explanations for why it could be TRUE and why it could be FALSE, recursing one level deeper on each. Then resolve the contradictions and state the most consistent conclusion." },
  { id:"usc", name:"Universal Self-Consistency", category:"ensemble", kind:"formal",
    shape:"sample N free-form outputs → pick most consistent",
    useCase:"Self-consistency for open-ended (non-vote-able) outputs.",
    orchestrated:true,
    instruction:"Produce your best free-form answer to the task.",
    note:"Engine: 3 samples → judge selects the answer most consistent with the ensemble. 4 calls." },

  /* ============ 7. OTHER PATTERNS ============ */
  { id:"analogical", name:"Analogical prompting", category:"patterns", kind:"formal",
    shape:"self-generate examples → solve",
    useCase:"Blank page; let the model recall relevant exemplars.",
    instruction:"First recall and write 2 RELEVANT EXAMPLES of similar solved problems (self-generated, with their solutions). Then solve the actual task using the patterns from your examples." },
  { id:"genknow", name:"Generated-Knowledge", category:"patterns", kind:"formal",
    shape:"list facts first → reason over them",
    useCase:"Knowledge-heavy tasks; ground before reasoning.",
    instruction:"First list the KEY FACTS/characteristics relevant to the task (8-10 bullet facts, no reasoning). Then reason over exactly that list to produce the answer." },
  { id:"pot", name:"Program-of-Thoughts / PAL", category:"patterns", kind:"formal",
    shape:"write code → (run) → answer",
    useCase:"Computation, counting, dates, anything code does better.",
    instruction:"Express the solution as a short program (pseudo-code or Python): variables for the givens, computation for the logic. Then trace its execution and report the program's output as the answer." },
  { id:"deep-breath", name:"Take-a-deep-breath / emotion prompt", category:"patterns", kind:"formal",
    shape:"meta-instruction nudges care",
    useCase:"Cheap quality nudge; baseline comparator.",
    instruction:"Take a deep breath and work on this problem step-by-step. This matters a great deal — be careful, thorough, and precise." },

  /* ============ 8. TRANSFER & ADAPTATION ============ */
  { id:"ladder", name:"Abstraction Laddering", category:"transfer", kind:"informal",
    shape:"↑ essence → cross → ↓ new domain",
    useCase:"Bridging two unlike things; repositioning.",
    instruction:"Climb the reference UP to its essence (thing → category → principle). CROSS to the target domain at the top rung. Climb DOWN into concrete target specifics. Show each rung." },
  { id:"structmap", name:"Structure Mapping (Gentner)", category:"transfer", kind:"formal",
    shape:"keep relations · drop attributes · translate expressions",
    useCase:"Deciding what to keep vs cut when adapting a reference.",
    instruction:"List the reference's traits. Tag each: ATTRIBUTE (property of the source itself → DROP or INVERT), RELATION (domain-free structure → TRANSFER intact), EXPRESSION (relation in source-specific form → TRANSLATE). Rebuild the concept in the target domain from the kept material." },
  { id:"blend", name:"Conceptual Blending", category:"transfer", kind:"formal",
    shape:"input A + input B → emergent blend",
    useCase:"Fusing two briefs/brands/moods into one concept.",
    instruction:"Select the goal-relevant pieces of the reference and of the target. Project both into a BLEND space and name the EMERGENT idea that exists in neither parent. Develop that idea." },
  { id:"bisoc", name:"Bisociation (Koestler)", category:"transfer", kind:"formal",
    shape:"frame A ✕ frame B → collision",
    useCase:"Genuine novelty; scroll-stoppers.",
    instruction:"Treat reference and target as two unrelated frames. COLLIDE them and build the concept around the clash itself. Keep the friction — do not smooth it into a bland mashup." },
  { id:"synectics", name:"Synectics (Gordon)", category:"transfer", kind:"informal",
    shape:"Direct/Personal/Symbolic/Fantasy analogies",
    useCase:"Creative rut; emotional angle for a dull subject.",
    instruction:"Generate four analogies for the task: DIRECT (how does another field solve this?), PERSONAL ('if I WERE the product, I feel…'), SYMBOLIC (a compressed paradox), FANTASY (the impossible ideal). Mine the best one into a concept." },
  { id:"scamper", name:"SCAMPER", category:"transfer", kind:"informal",
    shape:"Substitute·Combine·Adapt·Modify·Put·Eliminate·Reverse",
    useCase:"Variants of an existing concept.",
    instruction:"Run the concept through all 7 verbs — Substitute, Combine, Adapt, Modify/Magnify, Put-to-other-use, Eliminate, Reverse — one idea each. Then develop the strongest mutation." },
  { id:"triz", name:"TRIZ contradiction", category:"transfer", kind:"formal",
    shape:"resolve A-vs-B without compromise",
    useCase:"Two desirable traits fight (premium vs cheap…).",
    instruction:"Name the CONTRADICTION (we want X and Y but they conflict). Do NOT compromise. Resolve it by separating in time/space/scale or changing the mechanism, so both X and Y are fully delivered." },
  { id:"morph", name:"Morphological Analysis", category:"transfer", kind:"formal",
    shape:"dimensions × options → recombine",
    useCase:"Systematically generating many distinct concepts.",
    instruction:"Define 3-4 DIMENSIONS of the solution (e.g. tone, hero, era, medium) with 3 options each. Pick one unexpected-but-coherent cell per dimension and assemble that combination into the concept." },
  { id:"lateral", name:"Lateral / Random Entry (de Bono)", category:"transfer", kind:"informal",
    shape:"random stimulus → forced link",
    useCase:"Forcing originality on demand.",
    instruction:"Generate a RANDOM word unrelated to the task. Force a connection between it and the task and follow that connection to a non-obvious concept. State the random word." },
  { id:"persona", name:"Persona / Style Transfer", category:"transfer", kind:"informal",
    shape:"adopt source voice in target domain",
    useCase:"Fast tonal borrow ('make it feel like X').",
    instruction:"Solve the task AS IF created by the reference's maker: borrow their voice, restraint, and aesthetic decisions while fully serving the target's goal and audience." }
];

export const PRESET_CHAINS = [
  { name:"Full transfer pipeline", ids:["genknow","step-back","structmap","blend","scamper","self-refine"] },
  { name:"Concept explorer",       ids:["genknow","tot","cascade"] },
  { name:"Novelty push",           ids:["bisoc","synectics","lateral","self-refine"] },
  { name:"Verify hard answer",     ids:["cot","cove","self-consistency"] }
];

export const byId = id => FRAMEWORKS.find(f => f.id === id);
